export const prompts = [
  "Vector design of a swirling Turkish flag vortex, pulling in elements of technology, history, and culture. Circling the vortex are holographic projections of 'Turkiye', 'IZTECH', 'AI', and '100th', symbolizing the journey and achievements of the past century.",
  "Photo of a vast digital landscape with the Turkish flag waving gracefully in the wind. Embedded within the flag's patterns are the words 'Türkiye', 'İZTECH', and 'AI', shining brilliantly.",
  "Vector design of the Turkish flag, where the star and crescent are composed of interconnected AI circuits. Floating around are holographic projections of the words 'Türkiye', 'İZTECH', and 'AI'.",
  "Watercolor painting of the Bosphorus Bridge in Istanbul. The bridge lights up with 'Turkiye' and '100. YIL'. Beneath, AI boats sail with digital displays of the Turkish flag, and 'AI' is reflected in the water's shimmer.",
  "Illustration of a traditional Turkish pottery workshop. The ceramics showcase designs of '100. YIL', the Turkish flag, and 'AI' symbols. AI robotic artisans mold and paint the pottery, merging age-old crafts with modern tech.",
  "Illustration of a futuristic city skyline with holographic Turkish flags waving amidst advanced AI-driven structures. Above, 'IYTE Ai Society' is illuminated, with the date '29 Ekim' glowing prominently, celebrating Cumhuriyet Bayramı.",
  "Illustration of a futuristic city skyline with holographic Turkish flags waving amidst advanced AI-driven structures. Above, 'Iztech Ai Society' is prominently displayed, with the words 'October 29th Republic Day' glowing.",
  "Photo-themed representation celebrating the '100. yıl' milestone. The image showcases iconic symbols of the Cumhuriyet (Republic) and elements that highlight Türkiye's rich history and culture. Intertwined with these symbols are futuristic elements representing 'yapay zeka' (artificial intelligence), emphasizing the nation's progress in the field of AI.",
  "A depiction of the charming robot with a cartoonish design, its antenna glowing with AI symbols. The robot is excitedly presenting the birthday cake with '100. yıl' written on it towards an abstract representation of the Cumhuriyet (Republic). Surrounding the robot are more pronounced digital motifs representing artificial intelligence. The backdrop prominently features the Turkish flag, standing tall and proud.",
  "Illustration of a futuristic robot holding a birthday cake in its hands, facing us with a welcoming gaze. The cake has '100. yıl' inscribed on it, celebrating the milestone. In the background, the Turkish flag waves majestically, adding context and national pride to the scene.",
  "Illustration based on the third picture: A humanoid robot, emblematic of the advancements and aspirations of the IZTECH AI Society, gracefully opens a door. The inner side of the door offers a luminous display of artificial neural networks, symbolizing the AI innovations. Adjacent to the door, the Turkish flag and the IZTECH flag wave harmoniously side by side. The phrase 'Cumhuriyetimiz 100 Yaşında' (Our Republic is 100 Years Old) is elegantly integrated into the scene, celebrating the centenary of the Republic and the contributions of the IZTECH community.",
];
